steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/docker-demo:$TAG_NAME', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', 'gcr.io/$PROJECT_ID/docker-demo:$TAG_NAME', 'npm', 'start']
images: ['gcr.io/$PROJECT_ID/docker-demo:$TAG_NAME']
